{#
  Exposes the files written by the protobuf consumer as two views, which are
  declared as dbt sources in src/models/sources/raw_vehicle_telemetry.yml
  (generated by schema/generate.py):

    raw_<name>_files    one row per file: file_path, content (the bytes)
    raw_<name>_records  one row per Kafka record: file_path plus the fields
                        of kafka.v1.KafkaRecord, with the message itself
                        still serialized in `value`

  They are (re)created by on-run-start hooks in dbt_project.yml, so they
  always point at the current raw_path and descriptor. Files that aren't a
  valid KafkaRecordBatch are skipped in the records view (PERMISSIVE mode);
  the source tests report them.
#}
{% macro create_raw_schema() %}
  create schema if not exists {{ target.schema }}
{% endmacro %}

{% macro create_raw_files_view(name='vehicle_telemetry') %}
  create or replace view {{ target.schema }}.raw_{{ name }}_files as
  select path as file_path, content
  from {{ raw_protobuf_files() }}
{% endmacro %}

{% macro create_raw_records_view(name='vehicle_telemetry') %}
  create or replace view {{ target.schema }}.raw_{{ name }}_records as
  select file_path, record.*
  from (
    select
      file_path,
      explode(
        -- emit.default.values: proto3 doesn't store zero values, so without
        -- it partition 0 and offset 0 would come back as NULL.
        from_protobuf(
          content, 'kafka.v1.KafkaRecordBatch', '{{ var("descriptor_path") }}',
          map('mode', 'PERMISSIVE', 'emit.default.values', 'true')
        ).records
      ) as record
    from {{ target.schema }}.raw_{{ name }}_files
  ) as batches
{% endmacro %}
