"""Generates code and mappings from the .proto files in schema/proto.

    python schema/generate.py

Writes to schema/generated/ (not committed, recreated on every run):

    vehicle/v1/vehicle_telemetry_pb2.py   Python classes, generated by protoc
    vehicle/v1/vehicle_telemetry_pb2.pyi  Type hints for editors
    kafka/v1/kafka_record_pb2.py          The file format of the protobuf consumer
    elk/options_pb2.py                    The custom (elk.field_type) option
    descriptors/descriptor_set.desc       The compiled schema, generated by protoc;
                                          Spark's from_protobuf decodes with it
    elasticsearch/index_template.json     Elasticsearch index template

and, when the dbt project is next to it, the dbt source tests that check the
archived messages against the schema (committed, so they can be reviewed):

    dbt/src/models/sources/raw_vehicle_telemetry.yml

The Docker images run this script while they are built, so after changing a
.proto file, `docker compose up -d --build` is all it takes.

Configuration (environment variables):
    MESSAGE_TYPE     default: vehicle.v1.VehicleTelemetry
    INDEX_PATTERN    default: vehicle-telemetry-*
    ARCHIVE_NAME     default: vehicle_telemetry (names the dbt source tables)
    DBT_SOURCES_DIR  default: dbt/src/models/sources, if the dbt project exists
"""

import json
import os
import shutil
import sys
from pathlib import Path

import grpc_tools
from grpc_tools import protoc

SCHEMA_DIR = Path(__file__).resolve().parent
PROTO_DIR = SCHEMA_DIR / "proto"
GENERATED_DIR = SCHEMA_DIR / "generated"
DESCRIPTOR_SET = GENERATED_DIR / "descriptors" / "descriptor_set.desc"
# The .proto files that ship with protobuf, like google/protobuf/timestamp.proto.
WELL_KNOWN_PROTOS_DIR = Path(grpc_tools.__file__).parent / "_proto"

MESSAGE_TYPE = os.getenv("MESSAGE_TYPE", "vehicle.v1.VehicleTelemetry")
INDEX_PATTERN = os.getenv("INDEX_PATTERN", "vehicle-telemetry-*")
ARCHIVE_NAME = os.getenv("ARCHIVE_NAME", "vehicle_telemetry")
DBT_PROJECT_DIR = SCHEMA_DIR.parent / "dbt"
DBT_SOURCES_DIR = os.getenv("DBT_SOURCES_DIR") or (
    str(DBT_PROJECT_DIR / "src" / "models" / "sources") if DBT_PROJECT_DIR.is_dir() else None
)


def generate_python() -> None:
    proto_files = sorted(str(p.relative_to(PROTO_DIR)) for p in PROTO_DIR.rglob("*.proto"))
    exit_code = protoc.main(
        [
            "protoc",
            f"--proto_path={PROTO_DIR}",
            f"--proto_path={WELL_KNOWN_PROTOS_DIR}",
            f"--python_out={GENERATED_DIR}",
            f"--pyi_out={GENERATED_DIR}",
            # A binary FileDescriptorSet with all .proto files, including the
            # ones they import (like google/protobuf/timestamp.proto).
            f"--descriptor_set_out={DESCRIPTOR_SET}",
            "--include_imports",
            *proto_files,
        ]
    )
    if exit_code != 0:
        sys.exit(f"protoc failed with exit code {exit_code}")
    print(f"Generated Python code and {DESCRIPTOR_SET.relative_to(SCHEMA_DIR)} for {', '.join(proto_files)}")


def generate_index_template(message_type: type) -> None:
    from telemetry_schema import elk

    properties = elk.index_properties(message_type.DESCRIPTOR)
    # Fields added outside the protobuf message: @timestamp by Logstash, and
    # the Kafka coordinates by the ELK consumer.
    properties["@timestamp"] = {"type": "date"}
    properties["kafka"] = {
        "properties": {
            "topic": {"type": "keyword"},
            "partition": {"type": "integer"},
            "offset": {"type": "long"},
        }
    }
    template = {
        "index_patterns": [INDEX_PATTERN],
        "template": {
            "settings": {"number_of_shards": 1, "number_of_replicas": 0},
            "mappings": {"properties": properties},
        },
        "_meta": {"generated_from": message_type.DESCRIPTOR.full_name},
    }
    path = GENERATED_DIR / "elasticsearch" / "index_template.json"
    path.parent.mkdir(parents=True)
    path.write_text(json.dumps(template, indent=2) + "\n")
    print(f"Generated {path.relative_to(SCHEMA_DIR)}")


def generate_dbt_source_tests(message_type: type) -> None:
    from telemetry_schema import dbt_tests, message_class

    message = message_type.DESCRIPTOR
    record = message_class("kafka.v1.KafkaRecord").DESCRIPTOR
    path = Path(DBT_SOURCES_DIR) / f"raw_{ARCHIVE_NAME}.yml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(dbt_tests.source_yaml(message, record, ARCHIVE_NAME, message.file.name))
    print(f"Generated {path}")


def main() -> None:
    shutil.rmtree(GENERATED_DIR, ignore_errors=True)
    DESCRIPTOR_SET.parent.mkdir(parents=True)
    generate_python()

    sys.path.insert(0, str(SCHEMA_DIR))
    from telemetry_schema import message_class

    message_type = message_class(MESSAGE_TYPE)
    generate_index_template(message_type)
    if DBT_SOURCES_DIR:
        generate_dbt_source_tests(message_type)


if __name__ == "__main__":
    main()
